### ISSUE TITLE
Folder with special characters: UnicodeEncodeError

### ISSUE THREAD

**Issue by aapo** [PicciMario/iPhone-Backup-Analyzer-2#9]
Backup has folder with non-latin alphabet, eg Documents/فوتبال
Version: 3fd0dfa0d67e4eddb1e882fcff9f980f4903a107

```
Traceback (most recent call last):
  File "main.py", line 871, in openBackupGUI
    self.openBackup(newBackupPath)
  File "main.py", line 890, in openBackup
    self.readBackupArchive()
  File "main.py", line 1651, in readBackupArchive
    path = str(path_u[0])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-21: ordinal not in range(128)
```

**Comment by aapo** [comment]
Seems this can be handled with the same way as in row 1667. 

```
--- a/main.py
+++ b/main.py
@@ -1648,7 +1648,7 @@ class IPBA2(QtGui.QMainWindow):
                                paths = self.cursor.fetchall()

                                for path_u in paths:
-                                       path = str(path_u[0])
+                                       path = str(path_u[0].encode("utf-8"))

                                        if (len(domain_names) > 1):
                                                newPath = QtGui.QTreeWidgetItem(newDomain)
```

And then question is will row 1637 (domain_name = str(domain_name_u[0])) break then? Or some other str()?

**Comment by PicciMario** [comment]
hi!

wow, thanks for your bug reports, they are really interesting! sadly it's
been a while since I worked on iPBA2, and now the project is a little on
hold.. I've been working on other projects, and honestly I hardly remember
the details.
I'll ask you: could you try all your suggested edits and collect them in a
github pull request? That would be great! Of course, feel free to write for
any question should arise.

Thanks!

Mario

## Mario Piccinelli

"Dreamers come and go, but a dream's forever
Freedom for all minds, let us go together
Neverending ways, got to roam forever

## Always carry on!"

Mail/Gtalk: mario.piccinelli@gmail.com
Web/curriculum: www.mariopiccinelli.it

## Mobile: +39 392/2488673

Confidentiality Notice: This message, together with its annexes, contains
strictly confidential information and is destined only to the addressee(s)
identified above who only may use it under his/their responsibility. Anyone
who receives this message by mistake or reads it without entitlement is
forewarned that keeping, copying, disseminating or distributing this
message to persons other than the addressee(s) is strictly forbidden.
